generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      ArJobQueue
    theme:            default

    fields:
      state:           { name: State } 
      mystate:         { name: State } 
      created_at:      { name: Created at }
      end_at:          { name: Completed at }
      description:     { name: Description, type: textarea_tag, params: size=70x10 }

    list:
      title: Jobs Log
      actions: []
      sort: [id, desc]
      display: [=id, _mystate, created_at, description, end_at]
      filters: [created_at, end_at]
      max_per_page: 50

    edit:
      display: [=id, _mystate, created_at, description, end_at]
