################################################################
#!!!                                                        !!!#
#!!! WARNING: This file is automatic generated.             !!!#
#!!!                                                        !!!#
#!!! In order to modify this file change the content of     !!!#
#!!!                                                        !!!#
#!!!    /module_template/call_report_template               !!!#
#!!!                                                        !!!#
#!!! and execute                                            !!!#
#!!!                                                        !!!#
#!!!    php asterisell activate                             !!!#
#!!!                                                        !!!#
################################################################

exportToCsvSuccess:
  has_layout: false
  http_metas:
    cache-control: private
    pragma: private
    content-type: text/csv; charset=utf-8
    content-disposition: inline; filename="export.csv"

exportToExcelSuccess:
  has_layout: false
  http_metas:
    cache-control: private
    pragma: private
    content-type: application/msexcel; text/csv; charset=utf-8
    content-disposition: inline; filename="export.csv"
# NOTE:
#
# cache-control "private" and pragma "private" are needed
# as a workaround for bug
#
# http://support.microsoft.com/kb/323308/en-us

getSvgSuccess:
  has_layout: false
  http_metas:
    content-type: image/svg+xml

