################################################################
#!!!                                                        !!!#
#!!! WARNING: This file is automatic generated.             !!!#
#!!!                                                        !!!#
#!!! In order to modify this file change the content of     !!!#
#!!!                                                        !!!#
#!!!    /module_template/call_report_template               !!!#
#!!!                                                        !!!#
#!!! and execute                                            !!!#
#!!!                                                        !!!#
#!!!    sh generate_modules.sh                              !!!#     
#!!!                                                        !!!#
################################################################


all:
  is_secure: on
  credentials: admin